### ISSUE TITLE
Add bilateral filter

### ISSUE THREAD

**Issue by theotherphil** [image-rs/imageproc#217]
Possibly the fast version here: http://www.shellandslate.com/download/fastmedian_5506.pdf

**Comment by csheaff** [comment]
Hi, may I presume no one is working on this currently? If not, might there be any new thoughts on an implementation?

**Comment by theotherphil** [comment]
I’m not working on this, and I’m not aware of anyone else working on it either.

**Comment by csheaff** [comment]
Thanks, I'm giving it a shot. I've taken a cursory look at the above approach and am curious if this was singled out for a particular reason. As mentioned in [_A Concise Review of Fast Bilateral Filtering_ (Das et al., 2017)](https://ieeexplore.ieee.org/document/8313790), going with a fast method typically involves some kind of trade off with accuracy. I hesitate to choose for the user what kind of trade off is acceptable and am curious if some other kind of module should be reserved for "fast" algorithms, such as OpenCV's [ximgproc](https://docs.opencv.org/master/db/d50/classcv_1_1ximgproc_1_1FastBilateralSolverFilter.html). Thoughts?

**Comment by theotherphil** [comment]
Great! Providing the option to the user seems ideal, but an implementation of either approach would be a valuable addition to this library.

**Comment by csheaff** [comment]
I believe I've successfully [implemented](https://github.com/csheaff/imageproc/blob/429bdf650f69d27b57b5e6cc97420365e9c347d1/src/filter/mod.rs#L101) a version for grayscale images, so feel free to assign this ticket to me. I figure the next step would be getting it to work for color images. If you have any broad suggestions for adjustments (where the function belongs, testing, benchmarking, etc), they would be most welcome.

**Comment by csheaff** [comment]
Getting ready to submit a pull request for a grayscale implementation. Question: would you profer that I commit a truth image to the repo with test function? I have created a test function using `compare_to_truth_with_tolerance` with a truth image generated by `skimage.restoration.denoise_bilateral` and it passes using a tolerance of 1 pixel. However, I imagine that having a truth image for every function won't be sustainable without blowing up the size of the repo. Thoughts?

**Comment by csheaff** [comment]
I submitted a pull request with the truth image. Feel free to chime in there regarding the above question.

**Comment by ripytide** [comment]
Can this issue be closed since it was added in #462?

**Comment by theotherphil** [comment]
I plan on leaving this open until we have a version that works on colour images

**Comment by theotherphil** [comment]
Colour support added in https://github.com/image-rs/imageproc/pull/606
