### ISSUE TITLE
Add images to readme and/or documentation

### ISSUE THREAD

**Issue by theotherphil** [image-rs/imageproc#224]
Show what the various functions do visually. Pretty pictures are more of a draw than text!

**Comment by theotherphil** [comment]
criterion-plot uses an interesting hack - the doc generation first runs cargo test and then links to the target directory from the docs. This lets you include images in the docs, and ensures that the images match the doctests which produce them. However, it also means that just running cargo doc will produce broken docs (so docs.rs, for example, will contain a load of broken links).

**Comment by lazypassion** [comment]
How would I go about modifying the docs to place example images?

**Comment by theotherphil** [comment]
I'm actually not sure how to add pictures to the documentation in a way that will work when rendered on docs.rs. Adding some images to the README is easier - just commit them to the repo and link to them.

**Comment by lazypassion** [comment]
What should the images demonstrate about the project because I can't imagine showing an example of most of the algorithms in the readme. It would probably be too much in one place.

**Comment by theotherphil** [comment]
Sorry for the slow replies.

I didn't have any particular plans for what to show - I was imagining just picking a few functions that produce interesting looking results and showing the outputs of those. The intention was just to add a bit of colour to the README rather than to provide an accurate overview of what is available in this crate.
