### ISSUE TITLE
Can't draw semi-transparent shapes

### ISSUE THREAD

**Issue by mark-summerfield** [image-rs/imageproc#261]
I want to be able to draw semi-transparent rectangles. I have tried doing this using colors with a suitable alpha channel. Take this code for example:
```rust
extern crate image;
extern crate imageproc;

use std::path::Path;
use image::{Rgba, RgbaImage};
use imageproc::drawing::draw_filled_rect_mut;

fn main() {
    let path = Path::new("1.png");
    let solid_white = Rgba([255u8, 255u8, 255u8, 255u8]);
    let blue = Rgba([0u8, 0u8, 255u8, 255u8]);
    let semi_red = Rgba([255u8, 0u8, 0u8, 127u8]);
    let mut img = RgbaImage::new(200, 200);
    draw_filled_rect_mut( // Solid white background
        &mut img, imageproc::rect::Rect::at(0, 0).of_size(200, 200),
        solid_white);
    draw_filled_rect_mut( // Solid blue square
        &mut img, imageproc::rect::Rect::at(25, 25).of_size(100, 100),
        blue);
    draw_filled_rect_mut( // Semi-transparent red square
        &mut img, imageproc::rect::Rect::at(75, 75).of_size(75, 75),
        semi_red);
    img.save(path).unwrap();
}
```
I expected this to draw a 200x200 square in solid white (which it does), then to draw a 100x100 solid blue square on top (which it does), then to draw a 75x75 semi-transparent red square that overlaps the blue and the white (which it does -- but not quite right). I expected the red to "show through" some blue where it overlaps the blue square and to "show through" some white (i.e., look pink) where it overlaps the white background.

But there is no show through at all.

Is it possible to achieve this effect? If so, where is it documented?

**Comment by HeroicKatora** [comment]
You could draw the transparent shape into a new image, then blend the two images together. While that should have the desired effect, it's memory and performance is suboptimal. The issue with the current approach is that internally the library just sets the color of all pixels when executing `draw_filled_rect_mut`.

I think your expectation is correct and the interface should allow specifying a blend mode, but at least make it clearer what happens.

**Comment by theotherphil** [comment]
This is not currently supported, but the Pixel trait has a [blend method](https://docs.rs/image/0.18.0/image/trait.Pixel.html#tymethod.blend) already so it should be easy to add.

Note however that I'm the main contributor to this library and won't be working on this any time soon. PRs are obviously welcome.

**Comment by mark-summerfield** [comment]
I'm only a beginner with Rust and I'm not very good with git either. However, I wrote this function based on the idea in your comment above, and it works for me:
```rust
/// Draw as much of a rectangle, including its boundary, as lies inside the image bounds, blending in the given color.
pub fn draw_blended_rect_mut<I>(image: &mut I, rect: Rect, color: I::Pixel)
where
    I: GenericImage,
    I::Pixel: 'static,
{
    let image_bounds = Rect::at(0, 0).of_size(image.width(), image.height());
    if let Some(intersection) = image_bounds.intersect(rect) {
        for dy in 0..intersection.height() {
            for dx in 0..intersection.width() {
                let x = intersection.left() as u32 + dx;
                let y = intersection.top() as u32 + dy;
                let mut pixel = image.get_pixel(x, y);
                pixel.blend(&color);
                unsafe {
                    image.unsafe_put_pixel(x, y, pixel);
                }
            }
        }
    }
}
```

**Comment by theotherphil** [comment]
Looks good to me! There's a bit of thought required about which drawing functions should support this, and whether we should blend everything automatically or require users to opt-in. The drawing functions in this library were originally aimed at just showing regions of interest in an image, e.g. for computer vision applications, so I didn't give any thought to alpha blending. There will be a performance impact from doing this everywhere, but we'd need to measure to see if it's significant.

**Comment by mark-summerfield** [comment]
My use case is for highlighting pieces of text (like using a highlighter pen when making notes), so semi-transparency is vital for me.

Two ideas occur to me on this.
(1) Just use the exisiting draw*rect*() functions and inside the function use the current code if the passed in color's alpha channel is 255, otherwise use the blending code. It makes the functions twice as long but means that people who want solild color only pay the price of one if statement.
(2) Have pairs of functions *filled* and *blended*.

I am happy to write the functions and do a PR if you like.

**Comment by HeroicKatora** [comment]
I don't think changing the current functions is a good idea. In their current form, they are useful and possibly used to overwrite the pixel contents of an image buffer.

Instead I think we should generalize over available blend modes instead, similar to how OpenGL allows selecting one. Possibly a trait like the following:

```
trait Canvas<P> {
  fn draw_pixel(&mut self, x: i32, y: i32, color: P);
}

/// A canvas that simply overwrites existing pixel values when drawing
struct Overwrite<I>(pub I);

/// A canvas that blends pixels when drawing
struct Blend<I>(pub I);

impl<I: GenericImage> Canvas<I::Pixel> for Overwrite<I> {
  draw_pixel(&mut self, x: i32, y: i32, color: I::Pixel) {
    self.0.put_pixel(x, y, color)
  }
}

impl<I: GenericImage> Canvas<I::Pixel> for Blend<I> {
  draw_pixel(&mut self, x: i32, y: i32, color: I::Pixel) {
    self.0.blend_pixel(x, y, color)
  }
}
```

Then we could implement the current drawing mechanisms on top of this, either as default implemented methods or by taking references in the draw methods.

**Comment by theotherphil** [comment]
@HeroicKatora I forgot to reply at the time but this sounds like a great idea to me.

**Comment by sinhpham** [comment]
@theotherphil the draw_text_mut and draw_text functions are still not using the new Canvas. Seems like it is because draw_text_mut calling image.get_pixel, which the Canvas trait doesn't provide.

Should we add get_pixel to the Canvas trait, or another approach is preferred? I can work on a PR for this.
