### ISSUE TITLE
Add contour finding algorithm 

### ISSUE THREAD

**Issue by MichaelMauderer** [image-rs/imageproc#317]
Something like https://docs.opencv.org/3.4/d3/dc0/group__imgproc__shape.html#ga95f5b48d01abc7c2e0732db24689837b

**Comment by mikemoraned** [comment]
FYI, I just opened https://github.com/image-rs/imageproc/issues/406 which is similar to what you'd like. Want to work on this together in some way?

**Comment by MichaelMauderer** [comment]
I'd love to, but I don't really have the spare capacity for it at the moment.
(I went the alternative route and used [opencv-rust](https://github.com/twistedfall/opencv-rust).)
