### ISSUE TITLE
Move to image-rs

### ISSUE THREAD

**Issue by theotherphil** [image-rs/imageproc#318]
https://github.com/image-rs

**Comment by bvssvni** [comment]
We are ready to go.

Will move in 24 hours (or more), unless there are any last objections.

**Comment by bvssvni** [comment]
This repository is now transferred to `image-rs`.

**Comment by bvssvni** [comment]
The next step is to transfer permissions to publish on crates.io. Here is the plan:

1. I will invite @fintelia and @HeroicKatora as private owners in case anything unexpected happens during the transition
2. I will add the Publish team
3. When there are 2 private owners on crates.io besides @theotherphil , I will remove the Piston team and myself

**Comment by bvssvni** [comment]
Done.

Closing.
