### ISSUE TITLE
Unable to use crate in new project: "could not find `window` in `imageproc`"

### ISSUE THREAD

**Issue by johanndev** [image-rs/imageproc#322]
System info: 
`Windows 10 1809 x64`
`rustc 1.34.1 (fc50f328b 2019-04-24)` 

Hi!
First of all, I'm completely new to rust and its ecosystem, so pardon if the answer to my question is super-obvious.

I try to use this crate to display an image on the screen. I started by cloning this repo and running the `display_image` example - everything worked fine, images are displayed correctly. Next, I created a new project (using `cargo new ...`) and copied the contents of the example `display_image.rs` into my new `main.rs`; I also copied the `window.rs` into my `src` dir and created a `lib.rs`:
```
#[cfg(feature = "display-window")]
pub mod window;
```

If I now run the build command, I get the following error message:
<pre><code>
PS C:\code\basic_image_processing> <b>cargo build --features display-window --verbose</b>
       Fresh nodrop v0.1.13
       Fresh cc v1.0.36
       Fresh cfg-if v0.1.7
       Fresh lazy_static v1.3.0
       Fresh memoffset v0.2.1
       Fresh scopeguard v0.3.3
       Fresh unicode-xid v0.1.0
       Fresh ucd-util v0.1.3
       Fresh utf8-ranges v1.0.2
       Fresh autocfg v0.1.2
       Fresh either v1.5.2
       Fresh adler32 v1.0.3
       Fresh rand_core v0.4.0
       Fresh lzw v0.10.0
       Fresh color_quant v1.0.1
       Fresh bitflags v1.0.4
       Fresh scoped_threadpool v0.1.9
       Fresh custom_derive v0.1.7
       Fresh crossbeam-utils v0.2.2
       Fresh filetime v0.2.5
       Fresh cmake v0.1.39
       Fresh thread_local v0.3.6
       Fresh regex-syntax v0.6.6
       Fresh inflate v0.4.5
       Fresh itertools v0.7.11
       Fresh rand_core v0.3.1
       Fresh gif v0.10.1
       Fresh arrayvec v0.4.10
       Fresh memchr v2.2.0
       Fresh conv v0.3.3
       Fresh proc-macro2 v0.4.30
       Fresh tar v0.4.25
       Fresh libc v0.2.54
       Fresh num-traits v0.2.6
       Fresh crc32fast v1.2.0
       Fresh encoding_rs v0.8.17
       Fresh byteorder v1.3.1
       Fresh winapi v0.3.7
       Fresh crossbeam-epoch v0.3.1
       Fresh rand_isaac v0.1.1
       Fresh rand_xorshift v0.1.1
       Fresh rand_hc v0.1.0
       Fresh aho-corasick v0.7.3
       Fresh quote v0.6.12
       Fresh num_cpus v1.10.0
       Fresh miniz-sys v0.1.11
       Fresh num-integer v0.1.39
       Fresh deflate v0.7.19
       Fresh stb_truetype v0.2.6
       Fresh ordered-float v1.0.2
       Fresh approx v0.3.2
       Fresh num-complex v0.2.1
       Fresh rand_pcg v0.1.2
       Fresh rand_os v0.1.3
       Fresh rand_chacha v0.1.1
       Fresh rand_jitter v0.1.4
       Fresh crossbeam-deque v0.2.0
       Fresh regex v1.1.6
       Fresh syn v0.15.34
       Fresh flate2 v1.0.7
       Fresh num-bigint v0.2.2
       Fresh num-iter v0.1.37
       Fresh rusttype v0.7.6
       Fresh unidiff v0.3.1
       Fresh rayon-core v1.4.1
       Fresh rand v0.6.5
       Fresh num-derive v0.2.5
       Fresh num-rational v0.2.1
       Fresh png v0.14.1
       Fresh num v0.1.42
       Fresh rayon v1.0.3
       Fresh tiff v0.2.2
       Fresh num v0.2.0
       Fresh jpeg-decoder v0.1.15
       Fresh image v0.21.1
       Fresh sdl2-sys v0.32.6
       Fresh imageproc v0.18.0
       Fresh sdl2 v0.32.2
   Compiling basic_image_processing v0.1.0 (C:\code\basic_image_processing)
     Running `rustc --edition=2018 --crate-name basic_image_processing src\main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"display-window\"" --cfg "feature=\"sdl2\"" -C metadata=43d6458ad0bf2db7 -C extra-filename=-43d6458ad0bf2db7 --out-dir C:\code\basic_image_processing\target\debug\deps -C incremental=C:\code\basic_image_processing\target\debug\incremental -L dependency=C:\code\basic_image_processing\target\debug\deps --extern basic_image_processing=C:\code\basic_image_processing\target\debug\deps\libbasic_image_processing-c5aa612398b78a42.rlib --extern image=C:\code\basic_image_processing\target\debug\deps\libimage-ef31b55a78b40cff.rlib --extern imageproc=C:\code\basic_image_processing\target\debug\deps\libimageproc-08d62c343592c58c.rlib --extern sdl2=C:\code\basic_image_processing\target\debug\deps\libsdl2-9f0a80aa6f178787.rlib -L C:\code\basic_image_processing\target\debug\build\sdl2-sys-b38cdfaeba01d250\out\lib`
error[E0432]: unresolved import `imageproc::window`
  --> src\main.rs:10:20
   |
10 |     use imageproc::window::display_image;
   |                    ^^^^^^ could not find `window` in `imageproc`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `basic_image_processing`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name basic_image_processing src\main.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"display-window\"" --cfg "feature=\"sdl2\"" -C metadata=43d6458ad0bf2db7 -C extra-filename=-43d6458ad0bf2db7 --out-dir C:\code\basic_image_processing\target\debug\deps -C incremental=C:\code\basic_image_processing\target\debug\incremental -L dependency=C:\code\basic_image_processing\target\debug\deps --extern basic_image_processing=C:\code\basic_image_processing\target\debug\deps\libbasic_image_processing-c5aa612398b78a42.rlib --extern image=C:\code\basic_image_processing\target\debug\deps\libimage-ef31b55a78b40cff.rlib --extern imageproc=C:\code\basic_image_processing\target\debug\deps\libimageproc-08d62c343592c58c.rlib --extern sdl2=C:\code\basic_image_processing\target\debug\deps\libsdl2-9f0a80aa6f178787.rlib -L C:\code\basic_image_processing\target\debug\build\sdl2-sys-b38cdfaeba01d250\out\lib` (exit code: 1)
</code></pre>

`Cargo.toml`:
```
[package]
name = "basic_image_processing"
version = "0.1.0"
authors = ["johanndev"]
edition = "2018"

[dependencies]
image = "0.21.0"
sdl2 = { version = "0.32", optional = true, default-features = false, features = ["bundled"] }
imageproc = "0.18.0"

[features]
default = []
display-window = ["sdl2"]
```

Can somebody give me a hint of what I'm missing here?

Thanks!

**Comment by martinlindhe** [comment]
You need to add features tag to the imageproc crate

something like 

```toml

[dependencies]
imageproc = { version = "0.18.0", default-features = false, features = ["display-window"] }

**Comment by HeroicKatora** [comment]
You should not have to create a `src/main.rs` and a `src/lib.rs` in the same project, usually. Something about your setup might be unconventional.

**Comment by johanndev** [comment]
I installed rust by running `rustup-init.exe` from https://www.rust-lang.org/tools/install. I went with the default settings (`default host triple: x86_64-pc-windows-msvc, default toolchain: stable`).

I tried removing 'lib.rs' and 'window.rs' and got the same error message.

**Comment by birktj** [comment]
I believe you should have:
```
imageproc = { version = "0.18.0", features = ["display-window"] }
```

This crate has:
```rust
#[cfg(feature = "display-window")]
pub mod window;
```

**Comment by birktj** [comment]
Actually what you probably really want is (see https://github.com/rust-lang/cargo/issues/633):
```toml


[features]
default = []
display-window = ["sdl2", "imageproc/display-window"]
```

**Comment by johanndev** [comment]
@birktj: Both version work for me! :)

Thank you very much for your help!
