### ISSUE TITLE
HistSet::incr and decr are unsound

### ISSUE THREAD

**Issue by 64** [image-rs/imageproc#325]
https://github.com/image-rs/imageproc/blob/master/src/filter/median.rs#L248

These functions should be marked as unsafe since incorrect x and y inputs would lead to an out of bounds memory access.

As a general note, I see many instances of `unsafe_get_pixel` throughout this crate which I strongly feel would be better served by a safe variant. The optimiser should be smart enough to optimise out bounds checks, as most instances I've seen are in the form:

```rust
for x in 0..width {
	for y in 0..height {
		// do stuff
		let pixel = unsafe { image.unsafe_get_pixel(x, y) };
	}
}
```

This would dramatically reduce the amount of unsafe code in this crate.

**Comment by theotherphil** [comment]
HistSet is private so I didn’t bother marking it as unsafe at the time, but I’d accept a PR making incr and decor unsafe.

Yes, there are a lot of unsafe pixel accesses. Probably too many, but many were added after benchmarking showed that they made a difference. If you can find examples where they make no difference I’ll happily accept PRs to remove them.

**Comment by theotherphil** [comment]
I've created https://github.com/image-rs/imageproc/issues/371 to audit all the uses of unsafe in this library.

See https://github.com/image-rs/image/issues/999#issuecomment-520539214 for benchmarks showing the slowdown from just replacing unchecked indexing with checked indexing.

**Comment by theotherphil** [comment]
Addressed in https://github.com/image-rs/imageproc/pull/580
