### ISSUE TITLE
Use cargo fmt?

### ISSUE THREAD

**Issue by windelbouwman** [image-rs/imageproc#343]
I just formatted my local copy with the command `cargo fmt`, which formats all sourcecode. It then appeared to me, that I changed a lot of files :).

Is it the goal to format all files with cargo fmt? One issue I see with this, is that matrices are not nicely formatted anymore. But then again, this rustfmt tool is really handy.

**Comment by theotherphil** [comment]
The files in this library were all run through rustfmt at some point, but the defaults have changed since. I'd happily accept PRs to update the formatting, but I'd like to maintain the formatting of the matrices.

**Comment by JohnTitor** [comment]
FWIW: this config is now outdated.

https://github.com/image-rs/imageproc/blob/4cf5abb1f82f0e8e929c35e66df80b42617dc643/rustfmt.toml#L1
