### ISSUE TITLE
Image translation test

### ISSUE THREAD

**Issue by hepek** [image-rs/imageproc#346]
https://github.com/image-rs/imageproc/blob/58adc520090000c36da98f59338d41d8e3e2faa6/src/affine.rs#L455

Is this code correct?
Moving this image:

            00, 01, 02;
            10, 11, 12;
            20, 21, 22;

By (1,1) should give us

            00, 00, 00;
            00, 00, 01;
            00, 10, 11;

And not 

            00, 00, 01;
            00, 00, 01;
            10, 10, 11);

As stated by the test code.

Similar issue in the nest test case too: test_translate_positive_x_negative_y.

**Comment by theotherphil** [comment]
This behaviour is deliberate (see the comment on https://docs.rs/imageproc/0.18.0/imageproc/affine/fn.translate.html), but I'd accept a PR if you wanted to change the function to set pixels without a pre-image to black.

**Comment by hepek** [comment]
Oh, OK. My bad, sorry.

I was trying to extend the affine module to support full projective transformations, so when I reused the tests I noticed the inconsistency.

I will come back with a pull request when I'm done.

Closing this issue.
