### ISSUE TITLE
Cannot compile project which depends on the latest versions of `image` and `imageproc`

### ISSUE THREAD

**Issue by silvia-odwyer** [image-rs/imageproc#348]
I recently started a project which relies on the latest versions of image and imageproc, that is:

- image (version 0.22.1)
- imageproc version (0.18.0)

However upon running my project, it no longer compiles when the image and imageproc dependencies are updated to the versions listed above.

If I change the version in my Cargo.toml of the image crate to 0.21.0, it compiles. 

Here is a minimum verifiable example:

**Cargo.toml**
```[package]
name = "imageproc_mve"
version = "0.1.0"
edition = "2018"

[dependencies]
image = "*"
imageproc = "*"
```

**main.rs**
```
extern crate image;
use imageproc::drawing::{draw_filled_rect_mut};
use imageproc::rect::Rect;
use image::{DynamicImage, Rgba};

fn main() {
    let mut img = image::open("image.PNG").unwrap();

    draw_filled_rect_mut(&mut img, 
                        Rect::at(30, 50).of_size(200, 300), 
                        Rgba([128u8, 134u8, 210u8, 255u8]));

}
```

By running this, I get the following error:

```
error[E0277]: the trait bound `image::DynamicImage: image::image::GenericImage` is not satisfied
 --> src\main.rs:9:5
  |
9 |     draw_filled_rect_mut(&mut img,
  |     ^^^^^^^^^^^^^^^^^^^^ the trait `image::image::GenericImage` is not implemented for `image::DynamicImage`
  |
  = note: required by `imageproc::drawing::rect::draw_filled_rect_mut`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: Could not compile `imageproc_mve`.
```

**Fix**
In order to fix this, I rolled back the `image` dependency in my Cargo.toml to `0.21.1` and the code compiled. 
Could you further investigate this issue, and see if my minimum verifiable example above produces the same error? 

I see that this crate depends on an older version of the image crate, and this could be causing the issue.

**Comment by HeroicKatora** [comment]
It seems the published `0.18.0` depends on `image: 0.21.2`. Output from `cargo tree`:

```text
…
└── imageproc v0.18.0
    ├── image v0.21.2
…
```
