### ISSUE TITLE
connected_components on wasm fails at size check

### ISSUE THREAD

**Issue by mikemoraned** [image-rs/imageproc#383]
### Bug

In current HEAD, and also in `0.18.0` (which is the version I am using), `imageproc::region_labelling::connected_components` does the following check:

```rust
if image_size >= 2usize.pow(32) {
  panic!("Images with 2^32 or more pixels are not supported");
}
```

However `usize` on wasm is 32 bits which means that `2usize.pow(32)` overflows and becomes `0`, so the check ends up being `if image_size >= 0` so fails on all images.

### Possible fix

If I understand the intent of this check correctly, it is a protection against usage of `image_size` later as the size of an array:

```rust
let mut output_labels = vec![0u32; image_size];
```

I think we can get the same protection by changing the check to:

```rust
if image_size >= usize::max_value() as u32 {
  panic!(
    "Images with more pixels than `usize` supports ({}) are not supported",
    usize::max_value()
  );
}
```

I've started on this approach here: https://github.com/mikemoraned/imageproc/pull/1 . If this fix/approach is acceptable then I'll turn it into a full PR against this repo and submit as a fix for this bug.

**Comment by HeroicKatora** [comment]
The protection is against having more than `u32::max_value()` components, not against an allocation. That's because the labels are tracked as `u32` and must be unique per component. Without having concrete evidence I think that `u64` labels would slow down the code for all cases that are not as large.

## Other fix

Check the bit count directly instead of comparing against `2 << 32`.

```
let used_bits = mem::size_of<usize>()*8 - image_size.leading_zeroes();
if used_bits >= 32 {
    panic!("Images with 2^32 or more pixels are not supported")
}
```

**Comment by CryZe** [comment]
`image_size > u32::max_value() as usize` should be the fastest way.

**Comment by mikemoraned** [comment]
An aside: it's actually quite hard / impossible to write a test for this as in current version of `image` library, which where the Image definition comes from, it's not possible to construct an image with a size which breaks the limit.

Shall I break out a separate `panic_if_bigger_than` function so that this can be tested?

**Comment by mikemoraned** [comment]
Actually, I had a look at the std library, and using `saturating_pow` may be a smaller change which still avoids overflow:

```
if image_size >= 2usize.saturating_pow(32) {
  panic!("Images with 2^32 or more pixels are not supported");
}
```

What do you think?

**Comment by HeroicKatora** [comment]
Since an image can have at most `usize / 2` gray pixels due to Rust's internal restrictions that might be an interesting alternative. It's a bit hacky so that fact deserves a comment in the implementation.

**Comment by mikemoraned** [comment]
I've created https://github.com/image-rs/imageproc/pull/386 which updates the tests speciically for `region_labelling` to run on wasm32 and default target, and then applied one of the fixes above.
