### ISSUE TITLE
Different behaviour from warp and warp_with

### ISSUE THREAD

**Issue by Palladinium** [image-rs/imageproc#393]
# Versions
image 0.22.3
imageproc 0.19.2
rustc 1.40.0-nightly (1423bec54 2019-11-05)

# Description
I'm encountering some really strange behaviour from `geometric_transformations::warp`.

For example, take this input image.
![input](https://user-images.githubusercontent.com/3919824/69025119-dc050c80-0a19-11ea-8482-dacac475b442.png)

It contains a rectangle that's been warped by a perspective transform, and I'd like to invert this transform to obtain the original rectangle. I know the (rough) position of the rectangle's corners, so I use `Projection::from_control_points` and `warp`:
```rust
use image::Rgb;
use imageproc::geometric_transformations::{warp, Interpolation, Projection};
type Image = imageproc::definitions::Image<Rgb<u8>>;

fn extract_rect(image: Image) -> Image {
    let w = image.width() as f32;
    let h = image.height() as f32;

    let src = [(17.0, 20.0), (640.0, 20.0), (571.0, 382.0), (75.0, 382.0)];
    let dst = [(0.0, 0.0), (w, 0.0), (w, h), (0.0, h)];

    let p = Projection::from_control_points(src, dst)
        .expect("Could not compute projection matrix")
        .invert();

    warp(
        &image,
        &p,
        Interpolation::Bilinear,
        Rgb([0, 0, 0]),
    ))
}
```
However, the output image is not what I expect, as it just looks like the input image but slightly translated:

![warp](https://user-images.githubusercontent.com/3919824/69025142-f212cd00-0a19-11ea-8ab3-77640c26bdf6.png)

What's more interesting, I've managed to obtain the result I was looking for by replacing `warp` with `warp_with`, and explicitly multiplying points with the transform:
```rust
use image::Rgb;
use imageproc::geometric_transformations::{warp_with, Interpolation, Projection};
type Image = imageproc::definitions::Image<Rgb<u8>>;

fn extract_rect(image: Image) -> Image {
    let w = image.width() as f32;
    let h = image.height() as f32;

    let src = [(17.0, 20.0), (640.0, 20.0), (571.0, 382.0), (75.0, 382.0)];
    let dst = [(0.0, 0.0), (w, 0.0), (w, h), (0.0, h)];

    let p = Projection::from_control_points(src, dst)
        .expect("Could not compute projection matrix")
        .invert();

    warp_with(
        &image,
        |x, y| p * (x, y),
        Interpolation::Bilinear,
        Rgb([0, 0, 0]),
    ))
}
```
Now the output image is this:

![warp_with](https://user-images.githubusercontent.com/3919824/69025152-fe972580-0a19-11ea-8515-211d03a30534.png)

Is `warp` applying the transform incorrectly, or am I misunderstanding how to use it?

**Comment by SirVer** [comment]
I encountered the exact same issue and the `warp_with` workaround did work well for me.

**Comment by leo60228** [comment]
`warp` will detect whether the projection is affine, translation, or a full projection and optimize based on this. `Projection::mul` does not. I'm guessing that the detection is broken.

**Comment by leo60228** [comment]
The detection is fine...
```rust
    let wt = |x, y| projection.map_projective(x, y);                                                                                    
    let wa = |x, y| projection.map_affine(x, y);                                                                                        
    let wp = |x, y| projection.map_translation(x, y);                                                                                   
```
