### ISSUE TITLE
[feature inquiry] Random color palette utils for visual debugging purposes

### ISSUE THREAD

**Issue by colbyn** [image-rs/imageproc#404]
It would be nice to have some random color palette generation utilities.

E.g. for displaying the output of `connected_components` is a more visually distinct manner using RGB values over shades of gray. 

In the Python world it seems to be used a lot in image preprocessing pipelines for ML stuff (at least in beginner tutorials). 

For example, using the `colourado` dependency, I've written this:

```rust
pub fn random_color_map(keys: HashSet<u32>) -> HashMap<u32, image::Rgb<u8>> {
    use colourado::{Color, ColorPalette, PaletteType};
    let palette = ColorPalette::new(keys.len() as u32, PaletteType::Random, false);
    let mut output: HashMap<u32, image::Rgb<u8>> = HashMap::new();
    for (key, ix) in keys.iter().zip(0 .. keys.len()) {
        let key = key.clone();
        if key == 0 {
            output.insert(key, image::Rgb([0, 0, 0]));
        } else {
            fn convert(x: f32) -> u8 {
                (x * 255.0) as u8
            }
            let red = convert(palette.colors[ix].red);
            let green = convert(palette.colors[ix].green);
            let blue = convert(palette.colors[ix].blue);

            output.insert(key, image::Rgb([red, green, blue]));
        }
    }
    output
}
```

So the colors can be remapped here for a given grayscale image (in this case called `components`):
```rust
let debug_colors = random_color_map(components.pixels().map(|p| p[0]).collect());
let debug_media = ImageBuffer::from_fn(media.width(), media.height(), |x, y| {
    let px_key = components.get_pixel(x, y).channels()[0];
    let color = debug_colors.get(&px_key).expect("missing color entry");
    color.clone()
});
```

I could probably implement a more convent function that just maps grayscale images to some RGB variant directly, without requiring the intermediate traversal steps.

Any interest in accepting this feature as a pull request?

**Comment by theotherphil** [comment]
Sure, this looks like a nice feature to have. Thanks!

**Comment by colbyn** [comment]
Okay WIP PR [image-rs/imageproc/pull/405](https://github.com/image-rs/imageproc/pull/405).
