### ISSUE TITLE
Add "Contour Following" (Simple)

### ISSUE THREAD

**Issue by mikemoraned** [image-rs/imageproc#406]
Context: as part of my Biscuits project I had a need to extract the borders from a set of connected components. I used the "square tracing algorithm" + "Jacob's stopping criterion" as that was sufficient for my context; see https://github.com/mikemoraned/biscuits/commit/beb5bafad9e706124f38a45a146c34a12e33dcc7#diff-4dbdcb36de9736e49bb8d6d7a7f96736 . Here's the final code I refactored this to: https://github.com/mikemoraned/biscuits/tree/master/garibaldi/biscuiting-lib/src/border

I now plan to rework this into a form that's not tied to my project and contribute into imageproc within the `region_labelling` module. I will aim to do this in a way which is extensible to other more complicated needs; the above algorithm only works for 4-connected regions.

**Comment by mikemoraned** [comment]
@theotherphil : FYI, re: https://github.com/image-rs/imageproc#how-to-contribute, I am planning on doing this.

**Comment by theotherphil** [comment]
Contour tracing was added in https://github.com/image-rs/imageproc/pull/430
