### ISSUE TITLE
Make rayon as optional dependency

### ISSUE THREAD

**Issue by beltegeuse** [image-rs/imageproc#418]
Hi, 

I have noticed that this (awesome) library uses rayon by default for certain operations (`equalize_histogram_mut` and `warp_inner`) which is fine but might be good to give the user to opt-out for such optimization. The main point to opt-out to rayon is to reduce (optionally) the number of dependencies.

I suggest to change inside `Cargo.toml`:
```toml
[features]
default = [ "rayon" ]
```
```toml
[dependencies]
rayon = { version = "1.3.0", optional = true }
```
Here, the "rayon" feature will be used as the default (so no change for regular users). But now people can opt-out by doing:
```toml
imageproc = {version = "*", default-features = false}
```

Regarding the code changes: it is possible to use regular or rayon iterators like:
```rust
pub fn equalize_histogram_mut(image: &mut GrayImage) {
    let hist = cumulative_histogram(image).channels[0];
    let total = hist[255] as f32;

    #[cfg(feature = "rayon")]
    let iter = image.par_iter_mut();
    #[cfg(not(feature = "rayon"))]
    let iter = image.iter_mut();
    iter.for_each(|p| {
        // JUSTIFICATION
        //  Benefit
        //      Using checked indexing here makes this function take 1.1x longer, as measured
        //      by bench_equalize_histogram_mut
        //  Correctness
        //      Each channel of CumulativeChannelHistogram has length 256, and a GrayImage has 8 bits per pixel
        let fraction = unsafe { *hist.get_unchecked(*p as usize) as f32 / total };
        *p = (f32::min(255f32, 255f32 * fraction)) as u8;
    });
}
```

I can do a PR if necessary. 

ps: Note that `image` crate also have rayon as a dependency due to `jpeg-decode`. You can inspect the dependency graph using `cargo tree`

**Comment by theotherphil** [comment]
A PR would be welcome, thanks!

**Comment by beltegeuse** [comment]
PR #419 has been merged. Closing the issue
