### ISSUE TITLE
Can't use `draw_text_mut` with emoji font

### ISSUE THREAD

**Issue by TomPridham** [image-rs/imageproc#424]
i'm trying to use this library to draw emoji on a picture. it is not working however. i copied the font example and was able to generate an image with `hello world` on it successfully. when i switch to using `NotoColorEmoji.ttf` and replace `hello world` with a few emoji, i am unable to draw anything to the canvas. there are no errors, just a black picture.

i'm not sure if it is something i am doing incorrectly or if the library can't handle emoji at this point in time. if the latter, i would be willing to take a stab at implementing if given some pointers.

i created an example repo with a picture from the normal test and one with the emoji test

https://github.com/TomPridham/emoji-test

**Comment by theotherphil** [comment]
This library relies on rusttype to compute the pixels within each glyph: https://github.com/image-rs/imageproc/blob/master/src/drawing/text.rs#L27

There's an open issue on that library to add support for emojis.

**Comment by TomPridham** [comment]
ah, bummer. thanks for the info. doesn't look like that's on the horizon for them anytime soon
