### ISSUE TITLE
imageproc depends on rulinalg 0.4.2 which contains a known vulnerability and is not maintained

### ISSUE THREAD

**Issue by foresterre** [image-rs/imageproc#426]
RUSTSEC advisory: [RUSTSEC-2020-0023](https://rustsec.org/advisories/RUSTSEC-2020-0023)
dependency: [rulinalg 0.4.2](https://crates.io/crates/rulinalg)
issue for dependency:  [rulinalg#201](https://github.com/AtheMathmo/rulinalg/issues/201)

imageproc depends on rulinalg 0.4.2 which contains a known vulnerability (originally reported by [Quaz](https://github.com/Qwaz) on February 11th). This is reported by cargo-audit and cargo-deny which results in failing  CI checks for [sic](https://github.com/foresterre/sic/runs/1041121925). In the relevant [issue](https://github.com/AtheMathmo/rulinalg/issues/201), it is noted that rulinalg has not been updated for about 4 years. After the issue was reported, the library author consecutively updated the [readme](https://github.com/AtheMathmo/rulinalg/commit/0ea49678d2dfa0e0a0df9cd26f49f6330aef80c4) to include "This library is no longer actively maintained", so it is likely that the vulnerability will not be fixed. 

I searched on GitHub for usages of `raw_slice` and `raw_slice_mut` by `imageproc` but couldn't find any. Assuming `rulinalg` doesn't use it itself, somewhere in a function which is called by `imageproc`, it may be that `imageproc` is not directly vulnerable. However, anybody using a RUSTSEC advisory checking tool like cargo-audit or cargo-deny will have failing CI builds by including `imageproc` as dependency. For that reason, while also knowing that `rulinalg` is not being maintained, it may still be beneficial to replace `rulinalg` with a library or fork which is not vulnerable. 

While I don't know about the status of PR #417, or its contents, (*getting a Projection by from_control_points makes program freezing*, #412), if it where to be accepted some day, it would solve this issue as a side effect. 

If desired, I would be happy to help with fixing this issue, where I can. Thanks in advance!

```
ID:       RUSTSEC-2020-0023
Crate:    rulinalg
Version:  0.4.2
Date:     2020-02-11
URL:      rustsec.org/advisories/RUSTSEC-2020-0023
Title:    Lifetime boundary for `raw_slice` and `raw_slice_mut` are incorrect
Solution:  No safe upgrade is available!
Dependency tree:
rulinalg 0.4.2
└── imageproc 0.21.0
```

<details>
<summary>detailed report</summary>
<pre>
error[RUSTSEC-2020-0023]: Lifetime boundary for `raw_slice` and `raw_slice_mut` are incorrect

┌── /github/workspace/Cargo.lock:89:1 ───
│
│ rulinalg 0.4.2 registry+https://github.com/rust-lang/crates.io-index
│ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ security vulnerability detected
│
= The affected version of `rulinalg` has incorrect lifetime boundary definitions for `RowMut::raw_slice`
 and `RowMut::raw_slice_mut`. They do not conform with Rust's borrowing rule and allows the user to
 create multiple mutable references to the same location. This may result in unexpected calculation
 result and data race if both references are used at the same time.
= URL: https://github.com/AtheMathmo/rulinalg/issues/201
= rulinalg v0.4.2
└── imageproc v0.21.0
</pre>
</details>

**Comment by theotherphil** [comment]
Fixed by https://github.com/image-rs/imageproc/pull/417
