### ISSUE TITLE
Parallelize map_colors/map_pixels/map_*

### ISSUE THREAD

**Issue by carrascomj** [image-rs/imageproc#429]
I am trying to find an _easy_ way to parallelize [`map_colors`](https://docs.rs/imageproc/0.21.0/imageproc/map/fn.map_colors.html). Does anyone has a solution for that?

From an user perspective, I believe that the easiest way would be to provide an iterator over colors/pixels/subpixels/whatever and then the user could wrap it with [rayon](https://docs.rs/rayon/1.4.0/rayon/)'s `par_iter`. It may be related to #395, but it hasn't moved lately.

**Comment by theotherphil** [comment]
Implemented in https://github.com/image-rs/imageproc/pull/602

**Comment by carrascomj** [comment]
Great work, thanks! The performance discussion in the PR was very interesting.
