### ISSUE TITLE
flag to disable rayon multithreading for wasm

### ISSUE THREAD

**Issue by maninkari** [image-rs/imageproc#465]
Is there a way to disable rayon multithreading when using this library? My code keeps breaking because of rayon, not sure if it is because of trying to run multithreading in wasm. Thanks!

 
```
let w = 200;
let h = 200;

let img = ImageBuffer::from_fn(w, h, |x, y| {
    let i = ((x + y) % 256) as u8;
    if (x + y) % 3 == 0 {
        image::Rgba([255, 0, 0, 255])
    } else {
        image::Rgba([i, i, i, 255])
    }
});
let (cx, cy) = (120.0, 140.0);

let c_rotation = Projection::translate(cx, cy)
* Projection::rotate(PI / 6.0)
* Projection::translate(-cx, -cy);

let _warped = warp(
    &img,
    &c_rotation,
    Interpolation::Bilinear,
    Rgba([0 as u8; 4])
);
```
<img width="650" alt="Screenshot 2021-05-06 at 01 28 45" src="https://user-images.githubusercontent.com/3520378/117225837-31e69380-ae0b-11eb-9eb9-3d4873f3208f.png">

**Comment by theotherphil** [comment]
There’s a ‘rayon’ feature flag that should do this - see https://github.com/image-rs/imageproc/pull/419

**Comment by maninkari** [comment]
Thank you, I managed to get rid of the error by doing this in Cargo.toml
`imageproc = { version = "0.22", default-features = false }`
