### ISSUE TITLE
Hough transform based line detection too slow

### ISSUE THREAD

**Issue by srinivaschitturi** [image-rs/imageproc#469]
Seems like there is a bottleneck in the accumulator calculation where for every point (x,y), a grid of r,theta is updated. (Lines 56-74 in hough.rs)
In python's opencv, the entire lines detection completes in about 20ms on my machine, while Rust takes close to 6-7 seconds to complete. 

I rewrote the accumulator logic in Golang using standard 2D slices, and that part runs in around 20ms. I suspect there is a bottleneck in rust implementation somewhere. I tried to reimplement it using Vectors in Rust instead of image.get_unsafe_pixel implementation that currently exists, but that apparently did not speed it up meaningfully.

**Comment by theotherphil** [comment]
Could you provide an example image and command line/calling code where you're seeing this?

**Comment by srinivaschitturi** [comment]
Can you try this one.
`

        extern crate image;
        use imageproc::hough::{detect_lines, LineDetectionOptions, PolarLine};
        use imageproc::edges::canny;
        use std::time::Instant;
        fn main() {
            let img = image::open("sample.png").unwrap().to_luma8();
            let options = LineDetectionOptions {
                vote_threshold: 40,
                suppression_radius: 8,
            };
            let edges = canny(&img, 50.0, 100.0);
            let time1 = Instant::now();
            let _lines: Vec<PolarLine> = detect_lines(&edges, options);
            let time2 = time1.elapsed();
            println!("{:?}", time2);
        }
`

`

        import cv2
        import numpy as np
        import time
          
        img = cv2.imread('sample.png')
        
        gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
          
        edges = cv2.Canny(gray,50,150,apertureSize = 3)
          
        time1 = time.time()
        lines = cv2.HoughLines(edges,1,np.pi/180, 40)
        time2 = time.time()
        print(time2- time1)

`

![sample](https://user-images.githubusercontent.com/12710665/132301147-789a9f31-cfaa-4984-bebb-f5c649d67b57.png)

**Comment by theotherphil** [comment]
Thanks. I'll have a look this weekend

**Comment by theotherphil** [comment]
Your example runs in 165ms in debug mode and 9ms in release mode for me. Quick check: are you building in release mode?

**Comment by srinivaschitturi** [comment]
I was building it in debug mode unfortunately. Just tried building in release and it takes just 12ms for me. Apologies for the mixup..

**Comment by theotherphil** [comment]
Aha, glad it was easy to resolve!
