### ISSUE TITLE
Add Contrast Normalization

### ISSUE THREAD

**Issue by Charles-Schleich** [image-rs/imageproc#470]
I am keen to implement a contrast normalization based on this wikipedia article:
https://en.wikipedia.org/wiki/Normalization_(image_processing)

`imageproc::contrast` seems like the right place to put the functions for linear and non-linear normalization.

I will work on this over the next couple of days.

**Comment by theotherphil** [comment]
Implemented in https://github.com/image-rs/imageproc/pull/587
