### ISSUE TITLE
Multi Channel Image

### ISSUE THREAD

**Issue by szandara** [image-rs/imageproc#474]
I am trying to work with multi-channel  images. In OpenCV this is supported by the generic cv::Mat type. Where you can pass an arbitrary number of channels. The use case is to upscale an image after ML inference which has 7 channels. (I am using tract_onnx which also does not offer any resize operation on their Tensors).

I have been browsing the docs and examples but I cannot seem to figure out how to do that. From what I have seen, the Pixel data structure only holds maximum of 4 channels and supports just some well known image structures.

Is there a way to do it and if so how?

Thanks a lot for the help

**Comment by theotherphil** [comment]
Not sure how useful a reply is after three years (!), but…

This is not currently possible. I have no plans to make this crate off of the types defined in the `image` crate in the near future so this depends on making their `Pixel` types more generic. There’s an issue for this https://github.com/image-rs/image/issues/1523 but I don’t expect much progress any time soon.
