### ISSUE TITLE
`drawing::draw_text{_mut}` should allow negative coordinates

### ISSUE THREAD

**Issue by mvirkkunen** [image-rs/imageproc#476]
Most (all?) other drawing functions accept negative coordinates but these two functions require `u32` coordinates. This makes it impossible to draw text that's partially off the top/left side of the image. Is there a reason these two functions are the only ones that don't allow negative coordinates, or would you accept a PR that changes the arguments to `i32`?

**Comment by theotherphil** [comment]
This has been fixed on master, but the crate has not had a release in ages. I’ll release a new version this weekend.

**Comment by mvirkkunen** [comment]
Oops, sorry about that! Didn't check master. Thanks!
