### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by piegamesde** [image-rs/imageproc#497]
Pleases put git tags on the commits that get released to crates.io.

**Comment by brainstorm** [comment]
Totally second this. 

@cospectrum, would you and your team be interested in accepting a PR with [`release-plz`](https://crates.io/crates/release-plz)? I'm using it at work for months now and solves quite a bit of release engineering [(example versioning issue)](https://github.com/image-rs/imageproc/issues/256#issuecomment-1998599388) headaches: https://github.com/umccr/htsget-rs/blob/main/.github/workflows/release.yml

**Comment by cospectrum** [comment]
> Totally second this.
> 
> @cospectrum, would you and your team be interested in accepting a PR with [`release-plz`](https://crates.io/crates/release-plz)? I'm using it at work for months now and solves quite a bit of release engineering [(example versioning issue)](https://github.com/image-rs/imageproc/issues/256#issuecomment-1998599388) headaches: https://github.com/umccr/htsget-rs/blob/main/.github/workflows/release.yml

Don't know about release-plz, I have no rights here. As for the new version of image=`0.25`, I have already tried to explain, quite common. Opened PR https://github.com/image-rs/imageproc/pull/556 for those who depend on the latest version of image and master of imageproc

**Comment by theotherphil** [comment]
I've tagged version 0.24 and will tag future versions. Thanks for the offer of a PR but I don't think I want to use release-plz.
