### ISSUE TITLE
Hint on how to support font fill transparency in `draw_text_mut()`

### ISSUE THREAD

**Issue by hrbrmstr** [image-rs/imageproc#508]
`draw_text_mut()` chooses between the existing Canvas pixel and font glyph pixel here:

https://github.com/image-rs/imageproc/blob/b7942657b1a370fc485507693ed4df1f8a116cb7/src/drawing/text.rs#L68-L72

I feel kind of daft, but I'm unsure how to modify this (into a local crate function) to support blending the pixel with the background based on the alpha channel setting. Any pointers (I don't need a full solution) would be great!

**Comment by theotherphil** [comment]
You should be able to implement any required blending logic via an implementation of the Canvas trait. See https://github.com/image-rs/imageproc/blob/0929335c17a08016ca1a0443dbb1e4d1b6a3f229/src/drawing/canvas.rs#L99 for an example.
