### ISSUE TITLE
Add generalizated convolution filter

### ISSUE THREAD

**Issue by vsuryamurthy** [image-rs/imageproc#520]
At the moment, there is only a filter3x3 available. I would like to add a function which is a generalization of filter3x3.
Here is the PR: https://github.com/image-rs/imageproc/pull/517

**Comment by willhansen** [comment]
I thought it was odd I couldn't find this feature

**Comment by theotherphil** [comment]
This is available as `Kernel::filter`

**Comment by ripytide** [comment]
I think one of the reasons it might not have been spotted is because it is an associated method to the `Kernel` struct which is rather inconsistent as nearly all image operations are free-standing functions.

I think making that function free-standing would be a good idea.

**Comment by theotherphil** [comment]
I’d accept a PR to make that change.
