### ISSUE TITLE
Add Dithering [Willing to do it myself]

### ISSUE THREAD

**Issue by AntonJoha** [image-rs/imageproc#523]
Hi, 

I'm working on an ESC/POS library for Rust to use with a thermal printer. Next step in the process is to print images. The problem is that the printer can print either black or white, nothing else. I'll therefore need to implement some kind of dithering algorithm. 

I could if anyone is interested then I could try to make it for this repository in the process. 
I don't have _that_ much free time at the moment and is new to dithering, so it would probably take a while to complete.

**Comment by willhansen** [comment]
Looks like the base "image" crate already has something: https://docs.rs/image/latest/image/imageops/colorops/fn.dither.html

**Comment by AntonJoha** [comment]
> Looks like the base "image" crate already has something: https://docs.rs/image/latest/image/imageops/colorops/fn.dither.html

Thanks for bringing this to my attention. I missed that it was already implemented.

Closing this as it's a solved issue
