### ISSUE TITLE
Interest for a parallel version of match_template?

### ISSUE THREAD

**Issue by stephanemagnenat** [image-rs/imageproc#524]
Hello,

For a personal project, I wrote a parallel version of `match_template`, keeping essentially the same algorithm but using a Rayon parallel iterator for the y coordinate and collecting the result.

If there is interest here, I'm happy to do a PR with my changes. It would be good to know whether this should be an addition or a replacement, and if some tests are needed.

kind regards

**Comment by stephanemagnenat** [comment]
I'll do a benchmark and report the results tomorrow, but I would say, close to the number of cores.

**Comment by stephanemagnenat** [comment]
The PR is ready: #527.

I went for simplicity, if we are all happy about this new feature, it might be possible to de-duplicate some code between the original and the parallel version, or even, only use the parallel version by just changing the loop type depending on the availability of rayon.

**Comment by stephanemagnenat** [comment]
Any maintainer to approve the PR?

**Comment by theotherphil** [comment]
Implemented in https://github.com/image-rs/imageproc/pull/527
