### ISSUE TITLE
adaptive_threshold lacks the delta parameter

### ISSUE THREAD

**Issue by stephanemagnenat** [image-rs/imageproc#532]
The OpenCV equivalent of [`adaptive_threshold`](https://docs.rs/imageproc/latest/imageproc/contrast/fn.adaptive_threshold.html) has delta parameter ([they call it C in the documentation](https://docs.opencv.org/4.x/d7/d1b/group__imgproc__misc.html#ga72b913f352e4a1b1b397736707afcde3)), which is necessary in many use cases.

Currently the imageproc equivalent miss it. I need it, so I rewrote the function. I'll be happy to contribute the extended version in a PR, maybe we can name it `adaptive_threshold_with_delta` and let the old one use the new version with 0 as delta. That way, the API is not broken.

What do you think?

**Comment by theotherphil** [comment]
This would a welcome addition if you’re still up for creating the PR. Thanks.

**Comment by theotherphil** [comment]
Added in https://github.com/image-rs/imageproc/pull/637
