### ISSUE TITLE
Expose more private functions

### ISSUE THREAD

**Issue by nan-mu** [image-rs/imageproc#544]
Can we expose more private functions? Such as hough::intersection_points which act as middleware.
Or if there is any reason I don’t know, please let me know.

**Comment by theotherphil** [comment]
Sure, which functions do you want to be exposed?

**Comment by nan-mu** [comment]
Great to see your reply.  This problem has been with me for a while. I can sort it out later and should submit a PR this week.

**Comment by nan-mu** [comment]
Now it seems like I only want to make hough::intersection_points public.

```patch
diff --git a/src/hough.rs b/src/hough.rs
index ce1a663..e731ab9 100644
--- a/src/hough.rs
+++ b/src/hough.rs
@@ -130,7 +130,7 @@ where
 /// or `None` if the line and image bounding box are disjoint. The x value of an intersection
 /// point lies within the closed interval [0, image_width] and the y value within the closed
 /// interval [0, image_height].
-fn intersection_points(
+pub fn intersection_points(
     line: PolarLine,
     image_width: u32,
     image_height: u32,
```

**Comment by theotherphil** [comment]
Ok, great - if you create a PR for this I’ll merge it. Thanks.
