### ISSUE TITLE
Template matching with a mask

### ISSUE THREAD

**Issue by F8RZD** [image-rs/imageproc#567]
open cv provides a mask argument for their template matching function 

mask specifies the pixels that can be ignored during the matching progress 

it's very useful for transparent or white background image template matching

I couldn't find any similar functionality here
 is it planned to be implemented?

any help would be appreciated

**Comment by cospectrum** [comment]
I'll try to implement

**Comment by cospectrum** [comment]
There is no need to guess

<img width="784" alt="template_matching_opencv" src="https://github.com/image-rs/imageproc/assets/96136086/1421081c-29ba-4856-b68d-f2253079644e">
