### ISSUE TITLE
support grayscale morphology operators

### ISSUE THREAD

**Issue by Morgane55440** [image-rs/imageproc#576]
currently the operators in the [morphology](https://docs.rs/imageproc/0.17.0/imageproc/morphology/index.html) module only do binary operations (background = 0, foreground = 255).

but when doing morphological operations on actual operations, it is often necessary to do greyscale operations, using the whole range of values available.

i would like to propose to add greyscale variants of all the currently existing functions, as well as a `Mask` Struct to replace the `Norm` arguments, allowing for user defined masks.

if that is something that seems appropriate to add, i would love to work on the implementation myself.

see [the wikipedia article on grayscale morphology](https://en.wikipedia.org/wiki/Mathematical_morphology#Grayscale_morphology)

**Comment by theotherphil** [comment]
That would be a welcome addition - thanks!

**Comment by theotherphil** [comment]
Implemented in https://github.com/image-rs/imageproc/pull/581
