### ISSUE TITLE
`Laplacian` is incorrect

### ISSUE THREAD

**Issue by cospectrum** [image-rs/imageproc#585]
The actual `Laplacian` can have `negative` values, and for a `GrayImage` the max value can be much `higher` than `255`. But the merged version https://github.com/image-rs/imageproc/pull/516 doesn't care about it. So I want to remove the `detector` and at least fix the `filter`. Also approximation of `Laplacian` is not documented, and `OpenCV` uses `[0, 1, 0, 1, -4, 1, 0, 1, 0]` by default.

**Comment by thecodergus** [comment]
I read your points, reviewed the literature I consulted a year ago (Digital Image Processing, Global Edition - Rafael C. Gonzalez and Richard E. Woods) and I say that it is correct as it is. The default value of OpenCV is the adjacency transform, if you read my previous constructor, the use of [0, 1, 0, 1, -4, 1, 0, 1, 0] was present as an optional situation, if OpenCV uses it as default, it was a decision of the developers, in the literature this is a secondary formula. As for what you mentioned about the real Laplacian being able to have negative values, I didn't understand your point very well, in a GrayImage the resulting value will never be greater than 255 or negative.

**Comment by cospectrum** [comment]
In GrayImage they will not be negative, since in this format the pixels are stored as u8. But it doesn't mean that values are correct.

**Comment by cospectrum** [comment]
If the input values are in `[0, 255]`, then after `Laplacian` (with `[0, 1, 0, 1, -4, 1, 0, 1, 1]` kernel) they can be in `[-1020, 1020]`.

**Comment by cospectrum** [comment]
See `horizontal_sobel`, for example. The input is `GrayImage`, but the output is `Image<Luma<i16>>` to make sure we don't loose the value.

**Comment by thecodergus** [comment]
> See `horizontal_sobel`, for example. The input is `GrayImage`, but the output is `Image<Luma<i16>>` to make sure we don't lose the value.

I understand your point, but for what the algorithm proposes and does is correct, no information will be lost

**Comment by cospectrum** [comment]
Do you think `laplacian_filter` is correct? Because I have `variance of laplacian` in the production, and current implementation from imageproc `master` just not gonna work for me, so I will continue to use my own implementation, which does not lose value.

**Comment by cospectrum** [comment]
https://docs.opencv.org/4.9.0/d5/db5/tutorial_laplace_operator.html

<img width="837" alt="laplace" src="https://github.com/image-rs/imageproc/assets/96136086/113f5d4d-dc3b-4abb-ab91-4f04d80109c1">

**Comment by thecodergus** [comment]
> https://docs.opencv.org/4.9.0/d5/db5/tutorial_laplace_operator.html
> <img alt="laplace" width="837" src="https://private-user-images.githubusercontent.com/96136086/326631268-113f5d4d-dc3b-4abb-ab91-4f04d80109c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDAyNjUsIm5iZiI6MTcxNDQzOTk2NSwicGF0aCI6Ii85NjEzNjA4Ni8zMjY2MzEyNjgtMTEzZjVkNGQtZGMzYi00YWJiLWFiOTEtNGYwNGQ4MDEwOWMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MDEyOTUzOTg0OGYwYjYxY2JiM2E4ZTE4Y2Y5ZWI5MDQwOTJiNzQxZTcyOGMyMDQyZmJjOWYzZTc4MWQzNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lJQnTuatTONfC4S53Npgks2RVbEPszpVYMcdEQ-rlck">

I understand, I removed my suggestion about this
