### ISSUE TITLE
Release version 0.25

### ISSUE THREAD

**Issue by theotherphil** [image-rs/imageproc#595]
I’ll release version 0.25 on May 14th.

**Comment by theotherphil** [comment]
I'll wait until https://github.com/image-rs/imageproc/pull/598 is merged before releasing a new version. No rush!

**Comment by cospectrum** [comment]
I wanna write proptests for https://github.com/image-rs/imageproc/pull/598

**Comment by cospectrum** [comment]
> I wanna write proptests for #598

They pass

**Comment by theotherphil** [comment]
Published.

@cospectrum docs.rs has successfully rendered your new LaTeX documentation: https://docs.rs/imageproc/latest/imageproc/template_matching/enum.MatchTemplateMethod.html :)
