### ISSUE TITLE
Rename arguments of `assert_pixels_eq`

### ISSUE THREAD

**Issue by cospectrum** [image-rs/imageproc#605]
Currently, the first argument is named as `actual` and the second as `expected`. But even in `imageproc` tests, someone has already messed up the order. For me, the standard output was very unexpected.
Therefore, I suggest simply renaming the arguments to `left` and `right`, similar to rust stdlib.

**Comment by ripytide** [comment]
If that order was unexpected why not just fix that probably accidental mistake?

**Comment by cospectrum** [comment]
This is a common mistake, everyone will make it at some point.

**Comment by ripytide** [comment]
Isn't it still useful to have a convention of argument order though? It makes reading the source code easier.

**Comment by cospectrum** [comment]
But you don't need a biased standard output for that, name a variable.
And there are situations when there is no actual or expected result, you just want to compare.

**Comment by ripytide** [comment]
Fair enough, I would still suggest fixing the wrongly ordered assert though for consistencies sake.

**Comment by theotherphil** [comment]
I prefer to have a consistent ordering of actual vs expected values in test definitions and error messages. I’ll leave this issue open until I’ve checked for other tests with back to front arguments in their assertions.
