### ISSUE TITLE
Rename `imageproc::map::map_colors()` to `map_pixels()`

### ISSUE THREAD

**Issue by ripytide** [image-rs/imageproc#631]
`map_colors()` is inconsistent with the rest of the mapping functions such as `map_pixels()` and `map_subpixels()`. Instead I think clearer naming would be to rename the current `map_pixels()` to `map_enumerated_pixels()` and then rename `map_colors()` to `map_pixels()`. 

This would then match `image`'s `pixels()` and `enumerate_pixels()` iterators.

**Comment by theotherphil** [comment]
The current naming was chosen for consistency with `image`. I’ve just checked and the `pixels()` function on `GenericImageView` still returns an iterator over both positions and values. However, this is inconsistent with `ImageBuffer::pixels()`, and the `ImageBuffer` naming makes more sense than the `GenericImageView` naming so I agree with your proposed change.

**Comment by theotherphil** [comment]
Implemented in https://github.com/image-rs/imageproc/pull/602
