### ISSUE TITLE
`Laplacian` from `master` is wrong

### ISSUE THREAD

**Issue by cospectrum** [image-rs/imageproc#649]
Why it's `[1, 1, 1, 1, -4, 1, 1, 1, 1]`, while in the doc it's `[0, 1, 0, 1, -4, 1, 0, 1, 0]`?

**Comment by cospectrum** [comment]
No, I think it's ok. We just have a bunch of laplacians now

**Comment by theotherphil** [comment]
Looks like it was broken accidentally in https://github.com/image-rs/imageproc/pull/611 and there are no tests for `laplacian_filter` so this wasn’t caught.

Let’s add a test alongside fixing the kernel definition.

**Comment by theotherphil** [comment]
The bug was added since the last release so no crate versions are impacted.

**Comment by theotherphil** [comment]
Fixed by https://github.com/image-rs/imageproc/pull/650
