### ISSUE TITLE
Add extra maintainers

### ISSUE THREAD

**Issue by ripytide** [image-rs/imageproc#679]
@theotherphil how would you feel about giving myself and @cospectrum (if they're interested) maintainer-level privileges and letting us merge PRs? Personally, I have not been submitting as many PRs as I want to make since there are already outstanding PRs that have yet to be merged/closed. This would come with the disadvantage that some things you might disagree with get merged, however, if that is the case then we can always rollback those things.

Maybe we could have a policy or something where all PRs are left open for at least 3-days so that any maintainer can in that time say they are opposed and then discuss further that PR until agreement or closure, otherwise if no maintainer opposed in that time-frame then it gets merged? I think this kind of policy would work well for this kind of niche low-maintainer-bandwidth project whilst still allowing higher development velocity.

Feel free to just say no.

**Comment by theotherphil** [comment]
It’s a trade off but I’m more comfortable with a slower rate of development than with adopting a merge first approach.
